config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :books, except: [:index, :edit, :update] do
      resources :comments, only: [:create]
    end
  end

  root 'welcome#index'
  post '/login' => 'sessions#login'
  post '/logout' => 'sessions#logout'
  get '/search' => 'books#all'

  get '/recent_books' => 'books#recent'
  get '/popular_books' => 'books#popular'

  post 'users/:user_id/books/:book_id/upvote' => 'votes#upvote'
  post 'users/:user_id/books/:book_id/downvote' => 'votes#downvote'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :book
	belongs_to :commenter, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :books
	has_many :comments, foreign_key: :commenter_id
	has_many :votes, foreign_key: :voter_id

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: {with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\Z/i}
	#validates :password_digest, presence: true

  has_secure_password
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :book
	belongs_to :voter, class_name: 'User'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper :all
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def all
		if search_params
			@books = Book.search(search_params).order("title")
			if @books.any?
				@books
			else
				@books = Book.all.order("title")
			end
		end
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = params[:user_id]
		if @book.save
			redirect_to user_book_path(params[:user_id], @book)
		else
			render new_user_book_path(params[:user_id])
		end
	end

	def show
		@book = Book.find(params[:id])
		@comments = @book.comments
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
	end

	def recent
		@recent_books = Book.order(created_at: :desc)
	end

	def popular
		@popular_books = Book.joins(:votes).group("books.id").order("sum(votes.up_or_down) desc")
	end

	private

	def book_params
		params.require(:book).permit(:title, :author)
	end

	def search_params
		params.permit(:search)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@comment = Comment.new(comment_params)
		@comment.commenter_id = session[:current_user_id]
		@comment.book_id = params[:book_id]
		if @comment.save
			redirect_to user_book_path(params[:user_id], params[:book_id])
		else
			flash[:error] = 'Please enter a valid comment, stupid.'
			flash[:color] = 'invalid'
			render user_book_path(params[:user_id], params[:id])
		end
	end

	private 

	def comment_params
		params.permit(:comment_text, :parent_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:current_user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to '/'
    end
  end

  def logout
    session[:current_user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create!(user_params)
    session[:current_user_id] = @user.id
    redirect_to user_path(@user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path
  end

  def show
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,:password)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def upvote
		@vote = Vote.create(voter_id: session[:current_user_id], book_id: params[:book_id], up_or_down: 1)
		
		respond_to do |format|
      format.html
      format.json { render json: @vote.to_json }
    end
	end

	def downvote
		@vote = Vote.create(voter_id: session[:current_user_id], book_id: params[:book_id], up_or_down: -1)
		
		respond_to do |format|
      format.html
      format.json { render json: @vote.to_json }
    end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @books = Book.all
    @recent_books = Book.order(created_at: :desc).limit(5)
    @recent_comments = Comment.order(created_at: :desc).limit(5)
    @best_level = Book.get_highest_level_book
    @most_words = Book.get_most_words_book
    @best_word_length = Book.get_highest_word_length_book
    @best_syllable_length = Book.get_most_syllable_book
    @best_sentence_length = Book.get_longest_sentences_book
    @most_author = Book.group(:author).count.first
    @most_book = Book.group(:title).count.first



    @popular_books = Book.joins(:votes).group("books.id").order("sum(votes.up_or_down) desc").limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
	def nest(v, indent, comments)
		indent += 50
		if comments.empty?
			return v
		end
		comments.each do |comment|
			children = Comment.where("parent_id = ?", comment.id)
			v += render partial: "comment", locals: {comment: comment, indent: indent} 
			v = nest(v, indent, children)
		end
		v
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:current_user_id]
      @current_user ||= User.find_by_id(session[:current_user_id])
      return @current_user
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/welcome/index.html.erb
<center>
<h1 class='titleize'>Working Title</h1>

<ul>
  <li>
    <% if @books.any? %>
      <table>
        <tr>
          <td><h3>Highest reading level:</h3></td>
          <td><h4 class='titleize'><%= link_to @best_level.title.titleize, user_book_path(User.find(@best_level.user_id), @best_level) %></h4></td>
          <td><%= @best_level.reading_level %></td>
        </tr>
        <tr>
          <td><h3>Most words:</h3></td>
          <td><h4 class='titleize'><%= link_to @most_words.title.titleize, user_book_path(User.find(@most_words.user_id), @most_words) %></h4></td>
          <td><%= @most_words.word_count %></td>
        </tr>
        <tr>
          <td><h3>Longest average word length:</h3></td>
          <td><h4 class='titleize'><%= link_to @best_word_length.title.titleize, user_book_path(User.find(@best_word_length.user_id), @best_word_length) %></h4></td>
          <td><%= @best_word_length.avg_word_length.floor(2) %></td>
        </tr>
        <tr>
          <td><h3>Longest average syllable length:</h3></td>
          <td><h4 class='titleize'><%= link_to @best_syllable_length.title.titleize, user_book_path(User.find(@best_syllable_length.user_id), @best_syllable_length) %></h4></td>
          <td><%= @best_syllable_length.avg_syllable_length.floor(2) %></td>
        </tr>
        <tr>
          <td><h3>Longest average sentence length:</h3></td>
          <td><h4 class='titleize'><%= link_to @best_sentence_length.title.titleize, user_book_path(User.find(@best_sentence_length.user_id), @best_sentence_length) %></h4></td>
          <td><%= @best_sentence_length.avg_sentence_length.floor(2) %></td>
        </tr>
        <tr>
          <td><h3>Most uploaded author:</h3></td>
          <td><h4 class='titleize'><%= @most_author[0] %></td>
          <td><%= @most_author[1] %> uploads</td>
        </tr>
        <tr>
          <td><h3>Most uploaded book</h3></td>
          <td><h4 class='titleize'><%= @most_book[0].titleize %></h4></td>
          <td><%= @most_book[1] %> uploads</td>
        </tr>
      </table>
    <% end %>
  </li>
</ul>
  <br>
<ul>
  <li>
    <% if @recent_books.any? %>
      <table>
        <tr><th colspan='2'><h3><%= link_to "Recent Books", recent_books_path %></h3></th></tr>
        <% @recent_books.each do |book| %>
          <tr>
            <td><h3 class='titleize'><%= link_to book.title.titleize, user_book_path(User.find(book.user_id), book) %></h3></td>
            <td></h4>uploaded <%= book.created_at.localtime.strftime('%H:%M %m/%d/%Y') %></h4></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </li>

  <li>
    <% if @popular_books.any? %>
      <table>
        <tr><th colspan='2'><h3><%= link_to "Popular Books", popular_books_path %></h3></th></tr>
        <% @popular_books.each do |book| %>
          <tr>
            <td><h3 class='titleize'><%= link_to book.title.titleize, user_book_path(User.find(book.user_id), book) %></h3></td>
            <td><h4><%= book.votes.sum('up_or_down') %></h4></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </li>
</ul>

<% if @recent_comments.any? %>
  <h3 class='comment_header'>Recent Comments</h3>
  <% @recent_comments.each do |comment| %>
    <table class='comment_table'>
      <tr>
        <td><%= link_to comment.commenter.first_name.titleize, comment.commenter %> commented on <%= link_to comment.book.title.titleize, user_book_path(User.find(comment.book.user_id), comment.book) %> on <%= comment.created_at.localtime.strftime('%H:%M %m/%d/%Y') %>
      </td>
      </tr>
      <tr><td><%= comment.comment_text %></td></tr>
    </table>
  <% end %>
<% end %>
</center>